name: Bump Version

on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: '0'
                  
            - name: Bump version and push tag
              id: bump
              uses: anothrNick/github-tag-action@1.36.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  WITH_V: true
                  
            - name: Changelog
              uses: scottbrenner/generate-changelog-action@master
              id: Changelog
              

            - uses: ncipollo/release-action@v1
              with:
                draft: true
                body: | 
                  ${{ steps.Changelog.outputs.changelog }}
                tag: ${{ steps.bump.outputs.new_tag }}
                token: ${{ secrets.GITHUB_TOKEN }}
        
       
                    
