name: Bump Version

on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: '0'
                  
            - name: Bump version and push tag
              id: bump
              uses: anothrNick/github-tag-action@1.36.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  WITH_V: true
                  
            - name: Changelog
              uses: scottbrenner/generate-changelog-action@master
              id: Changelog
              
            - name: Create Release
              id: create_release
              uses: actions/create-release@latest
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                body: |
                  ${{ steps.Changelog.outputs.changelog }}
                draft: false
                prerelease: false
        
       
                    
